name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Job to merge from main to release
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code

      - name: Set up Git
        run: |
          git config --global user.name "Semantic Release"
          git config --global user.email "release@github.com"

      - name: Merge `main` into `release`
        id: merge-main-to-release
        run: |
          git fetch origin release
          git checkout release
          git rebase origin/main
          git push origin release --force

  release:
    runs-on: ubuntu-latest
    needs: merge

    steps:
      - uses: actions/checkout@v3
        name: Checkout Code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install -g semantic-release@23 @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
